### PR TITLE
Change url when clicking going to today

### LINKED ISSUE #207: "Back to today" button does not work while scrolling and the ripple hangs around
I think it might be good to scroll to the date if its already on "/timeline" without a selected date.

### PR DESCRIPTION
**Pull request by SaraVieira**
Closes #207

This PR fixes some weird behavior when navigating to today but changing the URL

### CODE REVIEW

File: src/features/timeline/TimelineIndexPage.js [hunk 1]
```diff
@@ -49,7 +47,7 @@ const CycleIndexPage = ({ entryId }) => {
           <DatePicker date={selectedDate} />
           <IconButton
             aria-label="Scroll to today"
-            onClick={() => navigate(TIMELINE.to)}
+            onClick={() => navigate(`/timeline/${entryIdFromDate(new Date())}`)}
```
Comment (raae) [inline src/features/timeline/TimelineIndexPage.js:50]: **suggestion: (non-blocking)** I think you can skip "/timeline/" and it will add it to the end of current path, makes sense in this use case I think...

**Review by raae — APPROVED** [review]

File: src/features/timeline/TimelineIndexPage.js (hunk 1 above)
Comment (SaraVieira) [reply src/features/timeline/TimelineIndexPage.js:50]: Up to you but i sometimes prefer to be more explicit so future sara does not get confused

Comment (raae) [reply src/features/timeline/TimelineIndexPage.js:50]: Makes sense, you do you

Comment (SaraVieira) [reply src/features/timeline/TimelineIndexPage.js:50]: Merged and closed the other one :D
