### PR TITLE
fix: Users are forced to opt in to the newsletter, closes #287

### LINKED ISSUE #287: Users are forced to say yes to the newsletter

### PR DESCRIPTION
**Pull request by raae**

### CODE REVIEW

File: src/features/profile/useProfile.js [hunk 1]
```diff
@@ -0,0 +1,45 @@
+import { useCallback } from "react"
+import { useUser } from "../user"
+
+const validate = (value) => {
```
Comment (raae) [inline src/features/profile/useProfile.js:4]: **thought:** Should at some point do some schema validation before calling userbase
